# Numpy
### fundamental library for scientific computing in python. provides support for arrays and matrices, collection of mathematical fucntions to operate on data structures

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.5/1.8 MB 1.5 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 3.0 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 26.1.1
    Uninstalling pip-26.1.1:
      Successfully uninstalled pip-26.1.1
Note: you may need to restart the kernel to use updated packages.


In [ ]:
#create arrays using numpy
#create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) # single dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
#create a 2D array

arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #this means 1 row and 5 columns and cannot reshape to (1,4) because there are 5 values


array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2)
print(arr2.shape) #2 rows and and 5 columns

[[1 2 3 4 5]
 [6 7 8 9 0]]
(2, 5)


In [13]:
np.arange(0,10,2).reshape(5,1) #reshape to 5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
## identity matrix or array
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [21]:
# numpy vectorised operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# element wise addition
print('addition', arr1+arr2)

#element wise subtraction
print('Subtraction', arr1-arr2)

##element wise multiply
print('multiply', arr1*arr2)

#element wise division
print('div', arr1/arr2)

addition [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
multiply [ 10  40  90 160 250]
div [0.1 0.1 0.1 0.1 0.1]


In [ ]:
# universal fucntion

arr=np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
# array slicing and indexing operation

arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print('array: \n', arr)

array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
print(arr[0])
print(arr[0][0])
print(arr[1:])
print(arr[1:,2:])
print(arr[1:, 1:3])

[1 2 3 4]
1
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


In [31]:
# modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [32]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [34]:
# statistical concept - normalisation
# change data to have eman of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [44]:
# logical operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data[data>5])
data[(data>=5) & (data>=8)]


[ 6  7  8  9 10]


array([ 8,  9, 10])