# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [20]:
## Assignment 1: Array Creation and Manipulation

'''1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 
    Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.'''

import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[1,2,3,4,5]])
print(arr.shape)
print(arr)
arr[0:,2]=1
print(arr)

arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,1,2,3,4]])
print(arr1.shape)
np.fill_diagonal(arr1, 0)
print(arr1)


(5, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]
[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]
 [ 1  2  1  4  5]]
(4, 5)
[[ 0  2  3  4  5]
 [ 6  0  8  9 10]
 [11 12  0 14 15]
 [16  1  2  0  4]]


In [ ]:
### Assignment 2: Array Indexing and Slicing

'''1. Create a NumPy array of shape (6, 6) with values from 1 to 36. 
Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.'''

arr=np.array([[1,2,3,4,5,36],[6,7,8,9,10,35],[11,12,13,14,15,34],[16,17,18,19,20,33],[21,22,23,24,25,32],[26,27,28,29,30,31]])
print(arr.shape)
print(arr)

arr[2:5,1:4]



(6, 6)
[[ 1  2  3  4  5 36]
 [ 6  7  8  9 10 35]
 [11 12 13 14 15 34]
 [16 17 18 19 20 33]
 [21 22 23 24 25 32]
 [26 27 28 29 30 31]]


array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [31]:
### Assignment 3: Array Operations

'''1. Create two NumPy arrays of shape (3, 4) filled with random integers. 
Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.'''

arr2 = np.random.randint(1,100,(3,4))
arr3 = np.random.randint(1,100,(3,4))

adi= arr2+arr3
print(f'The addition is:\n {adi}')

sub= arr2-arr3
print(f'The subtraction is:\n {sub}')

mul= arr2*arr3
print(f'The multiply is:\n {mul}')

div= arr2/arr3
print(f'The division is:\n {div}')


arr4 = np.random.randint(1,16, (4,4))
np.sum(arr4, axis=0)
np.sum(arr4, axis=1)

The addition is:
 [[ 57 115 158 158]
 [ 98 116 106 104]
 [130  63  67  62]]
The subtraction is:
 [[-43 -15  24 -34]
 [  2 -58 -32 -36]
 [ 44  33  23   0]]
The multiply is:
 [[ 350 3250 6097 5952]
 [2400 2523 2553 2380]
 [3741  720  990  961]]
The division is:
 [[0.14       0.76923077 1.35820896 0.64583333]
 [1.04166667 0.33333333 0.53623188 0.48571429]
 [2.02325581 3.2        2.04545455 1.        ]]


array([30, 36, 31, 34])

In [38]:
### Assignment 4: Statistical Operations
'''1. Create a NumPy array of shape (5, 5) filled with random integers. 
Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).'''


arr5= np.random.randint(1,110, (5,5))
mean= np.mean(arr5)
med= np.median(arr5)
stda= np.std(arr5)
vari= np.var(arr5)
print(f'{mean}, {med}, {stda},{vari}')

arr5= np.random.randint(1,9, (3,3))
mean= np.mean(arr5)
stda= np.std(arr5)

nor = (arr-mean)/stda
print(nor)

67.24, 69.0, 27.946062334432735,780.9824000000001
[[-2.19089023 -1.64316767 -1.09544512 -0.54772256  0.         16.97939928]
 [ 0.54772256  1.09544512  1.64316767  2.19089023  2.73861279 16.43167673]
 [ 3.28633535  3.8340579   4.38178046  4.92950302  5.47722558 15.88395417]
 [ 6.02494813  6.57267069  7.12039325  7.66811581  8.21583836 15.33623161]
 [ 8.76356092  9.31128348  9.85900604 10.40672859 10.95445115 14.78850905]
 [11.50217371 12.04989627 12.59761882 13.14534138 13.69306394 14.2407865 ]]


In [42]:
### Assignment 5: Broadcasting
'''1. Create a NumPy array of shape (3, 3) filled with random integers. 
Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. 
Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.'''

#What is broadcasting?
#NumPy automatically expands a smaller array to match the shape of a bigger one so operations
#  work without loops.

arr5= np.random.randint(1,100, (3,3))
row_add = np.array([1,2,3])
result = arr5+row_add
print(result)

arr6= np.random.randint(1,100, (4,4))
col = np.array([1,2,3,4]).reshape(4,1)

res = arr6 - col
print(res)


[[69 22 52]
 [54 92 50]
 [11 34  7]]
[[73 85 36  6]
 [62  8 24 71]
 [60 76 21 48]
 [58 64 88 48]]


In [53]:

### Assignment 7: Advanced Array Manipulation
'''1. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
Reshape the array to shape (1, 9) and then to shape (9, 1).

2. Create a NumPy array of shape (5, 5) filled with random integers. 
Flatten the array and then reshape it back to (5, 5).'''

arr = np.arange(1,10).reshape(3,3)
arr1 = arr.reshape(1,9)
arr2 = arr.reshape(9,1)
print(arr1 ,arr2)

arr = np.random.randint(1,100, (5,5))
arr1 = arr.flatten()
arr2 = arr.reshape(5,5)
print(arr1 ,arr2)



[[1 2 3 4 5 6 7 8 9]] [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[89 67 91 46 31 62 79 40 33 36 21 37 37  9 56 35 27 92 89 60 49 68 22 38
 79] [[89 67 91 46 31]
 [62 79 40 33 36]
 [21 37 37  9 56]
 [35 27 92 89 60]
 [49 68 22 38 79]]
